FROM alpine:latest
WORKDIR /mdathx
COPY ./mdathx ./mdathx.conf ./
RUN apk add --no-cache nginx nodejs \
    && mkdir logs
ENTRYPOINT ["/mdathx/mdathx", "--cache=/cache"]
CMD ["--cache=64", "--port=44300"]