FROM alpine:latest
WORKDIR /mdathx
COPY ./mdathx ./mdathx.conf ./package.json ./
RUN apk add --no-cache nginx nodejs npm \
    && npm install --production \
    && apk del npm \
    && mkdir logs
ENTRYPOINT ["/mdathx/mdathx", "--cache=/cache"]
CMD ["--cache=64"]